Rename 'enum type' to 'enum weather_type'
Rename 'enum type' to 'enum weather_type' to prevent conflict with
some CURL headers (fixes compilation on that systems).

That was the compile error:

 /usr/include/curl/curl.h:500: error: nested redefinition of 'enum type'
 /usr/include/curl/curl.h:500: error: redeclaration of 'enum type'